# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Thomas Lucas
tagline:             'Knowledge is Beautiful'
description:         'Made by Thomas Lucas'
url:                 http://th-lucas.github.io/
baseurl:             ''
gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"
excerpt_separator:   <!--more-->

# About/contact
test:               test

author:
  name:             Thomas Lucas
  github:           th-lucas
  email:            thomas.lucas88@gmail.com
  linkedin:         thomas-lucas-2a47898b

github:
  repo:           https://github.com/th-lucas/th-lucas.github.io

# Custom vars
version:             1.0.0
